name-template: "MQT DDSIM $RESOLVED_VERSION Release"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features and Enhancements"
    labels:
      - "feature"
      - "enhancement"
      - "usability"
      - "refactor"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "📄 Documentation"
    labels:
      - "documentation"
  - title: "📦 Packaging"
    labels:
      - "packaging"
  - title: "🧹 Code Quality"
    labels:
      - "code quality"
  - title: "🤖 CI"
    labels:
      - "continuous integration"
  - title: "⬆️ Dependencies"
    collapse-after: 5
    labels:
      - "dependencies"
      - "submodules"
      - "github_actions"
      - "pre-commit"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

template: |
  ## 👀 What Changed

  _Please refer to the [changelog](https://github.com/$OWNER/$REPOSITORY/blob/main/CHANGELOG.md) and the [upgrade guide](https://github.com/$OWNER/$REPOSITORY/blob/main/UPGRADING.md) for a structured overview of the changes._

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
