path_classifiers:
  test:
    - test
    - extern/qfr/test
    - extern/qfr/extern/dd_package/test
    - scripts
  library:
    - extern/qfr/extern/dd_package/extern/googletest
    - extern/qfr/extern/dd_package/extern/benchmark
    - extern/qfr/extern/json
    - extern/qfr/extern/pybind11
    - extern/qfr/extern/pybind11_json

extraction:
  cpp:
    prepare:
      packages:
        - python-pip
    after_prepare:
      - export PATH=~/.local/bin:$PATH
      - pip3 install cmake --user
      - cmake --version
    configure:
      command:
        - cmake -S . -B build -DBUILD_DDSIM_TESTS=ON -DBUILD_QFR_TESTS=ON -DBUILD_DD_PACKAGE_TESTS=ON -DBINDINGS=ON
    index:
      build_command:
        - cmake --build build --parallel 2
  python:
    python_setup:
      version: 3
      requirements:
        - qiskit-terra
