# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🐛 Bug Report
description: Report a problem or unexpected behavior
title: "🐛 <brief description of the issue>"
body:
  - type: markdown
    attributes:
      value: >-
        **Thanks for taking the time to report an issue!**

        ⚠ Before submitting:
        1. Search [existing issues](https://github.com/munich-quantum-toolkit/ddsim/search?q=is%3Aissue&type=issues) to avoid duplicates
        2. For questions or discussions, please use our [discussions forum](https://github.com/munich-quantum-toolkit/ddsim/discussions)
  - type: textarea
    attributes:
      label: System Information
      description: Please provide details about your environment
      placeholder: |
        - Operating System (including version):
        - MQT DDSIM version:
        - Python/C++ compiler version (if applicable):
        - Any relevant dependencies and their versions:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug Description
      description: Provide a clear and detailed explanation of the issue you're experiencing.
      placeholder: |
        What happened?
        What did you expect to happen instead?
        Include any error messages or unexpected behavior you observed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide specific steps to reproduce this issue
      placeholder: |
        1. Set up environment with '...'
        2. Configure workflow using '...'
        3. Execute command '...'
        4. Observe error/issue: '...'

        Include any relevant code snippets, workflow configurations, or input files that help demonstrate the problem.
    validations:
      required: true
