# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: ✨ Feature request
description: Suggest a new feature or improvement
title: "✨ <title>"
body:
  - type: markdown
    attributes:
      value: >
        **Thanks for helping improve this project by suggesting a feature!**

        ⚠ Before submitting:
        - Search [existing feature requests](https://github.com/munich-quantum-toolkit/ddsim/search?q=is%3Aissue&type=issues) to avoid duplicates
        - One feature per issue helps us track and implement ideas effectively

  - type: textarea
    attributes:
      label: Problem Statement
      description: >-
        Describe the problem you're facing and why it needs to be solved. What limitations are you encountering?
      placeholder: >-
        Currently, when I try to [action/task], I'm unable to [blockers/limitations].
        This creates problems because [impact/consequences].
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: >
        Describe your ideal solution. What would the feature look like? How would it work?
      placeholder: >-
        I'd like to see [feature/change] that would:
        - [benefit 1]
        - [benefit 2]
        - [example usage/scenario]
    validations:
      required: true
